# Simple workflow for deploying static content to GitHub Pages
name: Deploy to Pages
on:
  push:
    branches: ["master"]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v5

      - name: Sanitize referrer policy
        run: |
          curl -OL https://github.com/altbdoor/clean-links/releases/latest/download/clean-links-linux.tgz
          tar xzf clean-links-linux.tgz
          ./clean-links run --fix-all ./_site/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

      - uses: actions/deploy-pages@v4
        id: deployment
